### ISSUE TITLE
Running LayoutTests in GitHub Actions

### ISSUE THREAD

**Issue by annulen** [qtwebkit/qtwebkit#965]
Needs to be solved in the following order
- [ ] Experiment: record core dump in Docker in GitHub Actions (#961)
- [ ] Try running LayoutTests in Docker (#963)
- [ ] GHA: Build new qbat2 image each time JHBuild changes are pushed (#962)
- [ ] GHA: Incremental builds & tests in Docker image (#964)
